version: "3.9"

services:
  flask:
    build: ./app
    container_name: flask_app
    ports:
      - "5000:5000"   # 👈 Added for direct debugging
    networks:
      - app_net

  redis:
    image: redis:alpine
    container_name: redis_db
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
