version: "3.9"

services:
    app:
        build: ./app
        container_name: flask-app
        environment: 
         - REDIS_HOST=redis
        depends_on:
         - redis
         
    redis:
        image: mirror.gcr.io/redis:alpine
        container_name: redis-server
        volumes:
         - redis_data:/data
         
    nginx:
        image: mirror.gcr.io/nginx:alpine
        container_name: nginx-proxy
        volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
         - "8080:80"
        depends_on:
         - app
         
volumes:
    redis_data:
        