version: "3.8"
services:
  blue_app:
    build:
      context: .
      dockerfile: Dockerfile.blue
    container_name: blue_app
    ports:
      - "5001:5000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - blue_app
