name: Project-ci-cd-docker
on:
  push:
    paths:
      - "Project-cic-cd-docker/*"   
      - ".github/workflows/Project-cic-cd-docker" 
  pull_request:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubunutu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push docker images
        with:
          context: ./app
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/ci-cd-flask:latest
  deploy:
    runs-on: ubuntu:latest
    needs: build-and-push
    steps:
      - name: Pull and Run DOcker images
        run: >
          docker run -d -p 5000:5000
          ${{secrets.DOCKERHUB_USERNAME}}/ci-cd-flask:latest  
