name: Docker Build and Test

on:
    workflow_dispatch:
        
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
            
          - name: Setup Docker Buildx
            uses: docker/setup-buildx-action@v2
            
          - name: Login to Docker registry
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
              
          - name: Build and Push DOcker Images
            uses: docker/build-push-action@v4
            with: 
              context: ./Project-Hello-Docker
              file: ./Project-Hello-Docker/Dockerfile
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:latest
              
          - name: Run container
            run: |
              docker run -d -p 5000:5000 --name myapp ${{ secrets.DOCKERHUB_USERNAME}}/hello-docker:latest 
              for i in {1..10}; do
                if curl -f http://localhost:5000 | grep "Hello from Bharath"; then
                  echo "App is up!"
                  exit 0
                fi
                echo "Waiting for app..."
                sleep 5
              done
              echo "App did not start in time."
              docker logs myapp
              exit 1