---
name: Build Multistages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker:
      runs-on: ubuntu:latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build Docker image
          run: |
            docker build -t --name test-app flask-multistage .
        - name: Run Container
          run: |
            docker run -d -p 5000:5000 flaks-multistage
            sleep 5
            docker ps -a
        - name: Test app with curl
          run: |
            curl -f http://localhost:5000 || (docker logs test-app && exit 1)
        - name: Stop container and remove
          run: |
            docker stop test-app && docker rm test-app
            docker rmi flask-multistage
